### PR TITLE
Add support for `after-resume`

### PR DESCRIPTION
**Pull request by joezak11**
This request adds support for `sway-idle` `after-resume`.
This commit solves #73

### CODE REVIEW

**Review by nwg-piotr — CHANGES_REQUESTED** [review]
- main_hyprland.py -> load_settings() -> "after-resume" missing from the defaults dictionary
- "after-resume" value missing from numerous translations

See: https://nwg-piotr.github.io/nwg-shell/contribution

**Comment by joezak11** [comment]
I wasn't sure how you work with translations, but as I don't know those languages would google translate suffice?

**Comment by nwg-piotr** [comment]
> I wasn't sure how you work with translations, but as I don't know those languages would google translate suffice?

Sure. I asked people for help while translating all the stuff at the very beginning, but it took time. For just one phrase, use Google and forget. :)

**Review by nwg-piotr — APPROVED** [review]
Thanks.

**Pull request merged**
