### PR TITLE
french translations

### PR DESCRIPTION
**Pull request by giraudan**

### CODE REVIEW

**Comment by giraudan** [comment]
Hi! I'm currently doing the file for French and I have a couple of questions about some fields, can you give me a bit of context so that I can accurately translate please?

* `exclusive-zone`
* `exclusive-zone-tooltip`
* `keyboard-include-tooltip`
* `lock-screen-include-tooltip`
* `output`
* `pointer-device-include-tooltip`
* `start`
* `tap`
* `touchpad-device-include-tooltip`

Sometimes you refer to `hotspots`, what are they?

Also there seems to be a couple of copy-paste typos on those fields in `en_US.json`:

* `exit-menu-css-name`
* `exit-menu-css-name-tooltip`

**Comment by nwg-piotr** [comment]
Hi!

> exclusive-zone

If you place a window in the gtk-layer-shell exclusive zone, other windows will be moved away, so that they didn't cover your window. Example: panels/bars are usually in the exclusive zone.

> keyboard-include

The `keyboard` txt file, containing keyboard settings, which we include in the sway config file. "Includes" here are in general the config files that we include.

> Tooltips 

The tips that appear, when you point a GTK widget with the mouse pointer.

> output

The display name in the sway/wlroots meaning, e.g. eDP-1, HDMI-A-1, and so on.

> start

here means the beginning: align to "start" / "middle" or "center" / "end".

> tap

Like click, but on a touchpad.

> hotspot

Is the screen area that you need to point with the mouse pointer for the dock to appear.

> Also there seems to be a couple of copy-paste typos on those fields in en_US.json:

Yes, thank you. I'll fix them.

Thank you for your commitment!

**Review by nwg-piotr — CHANGES_REQUESTED** [review]
Almost perfect. Could you please remove either line 40 or 41?

**Comment by nwg-piotr** [comment]
LOL, I don't understand a word of French :) Thank you again.

**Review by nwg-piotr — APPROVED** [review]

**Pull request merged**
