### PR TITLE
Multiple language support

### PR DESCRIPTION
**Pull request by nwg-piotr**
Added support for translations. The `~/.local/share/nwg-shell/data` json file contains the `"interface-locale"` key, that is empty by default. It means: use auto-detected locale. Detection looks like this:

```python
lang = os.getenv("LANG").split(".")[0] if not shell_data["interface-locale"] else shell_data["interface-locale"]
```

which returns e.g. `pl_PL` for the `pl_PL.UTF-8` locale, __if no value found__ in the data file. Otherwise the saved value will be used. You may use the "Interface language" combo to save the value. This is supposed to work shell-wide in the future.

image

Currently available language files you'll find in the `langs` folder. For now those are:

- `en_US.json` (basic language)
- `pl_PL.json` (Polish translation)

Feel free to submit translations into the languages you speak. Use the `en_US.json` file as the base. 

@jovanlanik: how about `cs_CZ.json`, `sr_*.json`, or something else, when you have a spare hour?

### CODE REVIEW

**Comment by jovanlanik** [comment]
I'll see what I can do.

**Comment by jovanlanik** [comment]
Your English translation is missing the `below-clock` key.

**Comment by nwg-piotr** [comment]
Awww, shit... Thanks! Fixing now.

**Comment by nwg-piotr** [comment]
Wait, it's never used. I renamed it to `"under-clock"`.

**Comment by nwg-piotr** [comment]
@jovanlanik I added 5 new keys or so, to translate forgotten `updater.py`. Sorry about the inconvenience.

**Pull request merged**
