### PR TITLE
Powerbar

### PR DESCRIPTION
**Pull request by nwg-piotr**
Added support for the gtklock [powerbar module](https://github.com/jovanlanik/gtklock-powerbar-module).

@jovanlanik - thanks for adding it.

### CODE REVIEW

**Comment by jovanlanik** [comment]
Great to see! Maybe next I can implement a playerctl module and you can re-enable input inhibitor for gtklock?

**Comment by nwg-piotr** [comment]
> implement a playerctl module

As I said once: very good idea.

**Comment by jovanlanik** [comment]
I started work on it at https://github.com/jovanlanik/gtklock-playerctl-module. It's still not functional but I'll push out a release once I finish.

**Comment by nwg-piotr** [comment]
Very well. I'll remove the playerctl window from my nwg-lock script, as soon, as it's ready.

**Comment by jovanlanik** [comment]
image
Little preview...

**Comment by nwg-piotr** [comment]
Nice! Will the position be configurable?

**Comment by jovanlanik** [comment]
Yes

**Comment by jovanlanik** [comment]
I added docs for powerbar-module at https://github.com/jovanlanik/gtklock-powerbar-module/wiki

**Comment by nwg-piotr** [comment]
Very well. I'm just adding a possibility to use various gtklock configs & style sheet for shell presets.

**Comment by nwg-piotr** [comment]
> I added docs for powerbar-module at https://github.com/jovanlanik/gtklock-powerbar-module/wiki

One idea: if `show-labels=false`, the could show up anyway, as the tooltip text.

**Comment by jovanlanik** [comment]
I tried that 😅 but seems a problem with gtk-layer-shell prevents this...

**Comment by jovanlanik** [comment]
One other thing... I made it so that module options are available from the command-line.
For example `$ gtklock -m powerbar-module --powerbar-show-labels`.

**Comment by nwg-piotr** [comment]
Very nice, but I decided not to make predefined configs for presets, just style sheets. The user will have a single `config.ini`, and a possibility to add own configs, that will be used as the command argument, if found. Added the README file:

> If you'd like to have separate gtklock configs for different nwg-shell presets, create a config file for each one, under the names 'preset-0', 'preset-1' and so on in this folder.

**Comment by jovanlanik** [comment]
I assumed you would continue using command-line options from your wrapper and store the configuration yourself.
That way you completely avoid using the config file.

**Comment by nwg-piotr** [comment]
I wanted to avoid adding more GUI temporarily, but probably you're right. That's is a better solution.

**Comment by nwg-piotr** [comment]
But does it work yet?

```text
$ gtklock -m powerbar-module --powerbar-show-labels

** (gtklock:17705): CRITICAL **: 23:28:55.816: Option parsing failed: Nieznana opcja --powerbar-show-labels
```

**Comment by jovanlanik** [comment]
Should work on the latest master. You have to update both gtklock and the module.

**Comment by nwg-piotr** [comment]
It always results in version mismatch later. I'll better wait for packages, and focus on what's doable now: gtklock common settings and style sheets.

**Comment by nwg-piotr** [comment]
BTW: what does `linked-buttons` mean?

**Comment by nwg-piotr** [comment]
> One other thing... I made it so that module options are available from the command-line.

I assumed it's also available for the userinfo module. Am I right?

**Comment by jovanlanik** [comment]
> It always results in version mismatch later. I'll better wait for packages, and focus on what's doable on my side now.

Amazing work!
> BTW: what does `linked-buttons` mean?

image
image
> I assumed it's also available for the userinfo module. Am I right?

Yes but I changed some options. `round-image` was changed to `no-round-image` and `vertical-layout` to `horizontal-layout`. The reason is command-line flags have to be false by default... I'll update the documentation as well.
You can always see module options by running `$ gtklock -m userinfo-module --help-userinfo`.

**Comment by nwg-piotr** [comment]
Alright, I need to wait for final modules versions, if so. Anyway, the code on my side is ready to support config values as flags. At most, I'll have to rename them.

**Comment by nwg-piotr** [comment]
My css styles finally seem to match the presets, and I do like it.

`preset-1.css`

image

`preset-3.css`

image

**Comment by jovanlanik** [comment]
Looks great!

**Comment by jovanlanik** [comment]
The playerctl module should be functional now. You can test it with the packaged version of gtklock (1.3.6) or master, master will allow command-line options.

Current playerctl options are:
```ini
[playerctl]
art-size=64
position=top-center
```
If you set `art-size` to 0, it will be hidden. `position` can be one of `top-left`, `top-center`, `top-right`, `bottom-left`, `bottom-center`, `bottom-right`, `above-clock` or `under-clock`.

**Comment by jovanlanik** [comment]
And all modules together! Looks a bit crowded 😅

image

**Comment by nwg-piotr** [comment]
I'm curious to see it in action. Will give it a try tonight.

Wouldn't it be possible to place it in the corner?

**Comment by nwg-piotr** [comment]
It works, to some degree. I''m testing with the packaged gtklock version.

- Where does it take images from? I still see just the missing image icon. Even if I set `art-size=0`.
- The play/pause button works. Forward / backward buttons end up in memory dump.

**Comment by jovanlanik** [comment]
Try testing with master, I'm not sure if 1.3.6 works or not... I'll push out 1.3.7 soon.

**Comment by jovanlanik** [comment]
Also what players are you using? I only tested firefox and mpv, so it might have an impact.

**Comment by nwg-piotr** [comment]
music.youtube.com on Google Chrome and Audacity.

**Comment by jovanlanik** [comment]
> Where does it take images from? I still see just the missing image icon. Even if I set `art-size=0`.

The image is loaded from a URI in the metadata. You can view it by running `$ playerctl metadata`
It seems chrome doesn't provide an image. Here is my output on chromium 105 on music.youtube.com:
```
chromium mpris:length              371000000
chromium mpris:trackid             '/org/chromium/MediaPlayer2/TrackList/Track5100E01FD81EC22DACEF4ECCFAF68F98'
chromium xesam:album               
chromium xesam:artist              Black Sabbath
chromium xesam:title               Into the Void
```
Firefox on the other hand outputs:
```
firefox mpris:trackid             '/org/mpris/MediaPlayer2/firefox'
firefox xesam:title               Into the Void
firefox xesam:album               Master of Reality (2009 Remastered Version)
firefox xesam:artist              Black Sabbath
firefox mpris:artUrl              file:///home/lanikjo/.mozilla/firefox/firefox-mpris/9835_0.png
```
Same page, same track.

I also tested Audacious and had no problem with the image.
image
Metadata here:
```
audacious xesam:title               Voljela Me Nije Ni Jedna
audacious xesam:artist              Branimir Stulic
audacious xesam:album               Balegari Ne Vjeruju Sreci
audacious xesam:url                 file:///home/lanikjo/Downloads/Branimir%20Stulic%20-%20Balegari%20Ne%20Vjeruju%20Sreci%20%281990%29%20%5BFLAC%5D/Branimir%20Stulic%20-%2001.%20Voljela%20Me%20Nije%20Ni%20Jedna.flac
audacious mpris:length              184000000
audacious mpris:artUrl              file:///home/lanikjo/Downloads/Branimir%20Stulic%20-%20Balegari%20Ne%20Vjeruju%20Sreci%20%281990%29%20%5BFLAC%5D/folder.jpg
audacious mpris:trackid             '/org/mpris/MediaPlayer2/CurrentTrack'
```
Can you try running `$ playerctl metadata` with your players and see what you get?

**Comment by jovanlanik** [comment]
Also I fixed the missing image icon showing even when art-size is 0.

**Comment by nwg-piotr** [comment]
You're right, Firefox provides the image path. Unfortunately, it's useless on my setup, as it always crashes on sway reload, if my external keyboard is attached. Can't live w/o it, since the built-in MSI keyboard is horrible. :/

> Also I fixed the missing image icon showing even when art-size is 0.

It works.

> Try testing with master

Not tonight, sorry. I am leaving for a long journey at six in the morning and it's already 2 am. I'll take a look at it as soon as I'm back.

**Pull request merged**
